# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 763f74e4e87fd3b9b48a8562db7e693941dcc64a424b4480163b77f423294062a6f1b8416e17410c27be0db3ab721a256e44bf393aab2f91b10bcdd38595150b

test:
  secret_key_base: 6ab11ef433e8d9090fec6ee95543ba0d9100daefc910c33de091d9bbe555a41a914ab911b004b3ba150f463f15eb92cefaa641e0db5bf2849cf0e2021d410e13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
